[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.(js|css|png|jpg|jpeg|svg|webp|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
